name: Deploy Environment

on:
  pull_request:
    types:
      - closed  # Trigger when a pull request is closed (including merged)

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Default permission for accessing the repo

jobs:
  # Step 1: Bootstrap Backend Resources (if not already done)
  backend:
    if: github.event.pull_request.merged == true && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/main')
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} # Use the branch name as environment
    outputs:
      environment: ${{ steps.setenv.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment based on branch
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
            echo "environment=qa" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=main" >> $GITHUB_ENV
            echo "environment=main" >> $GITHUB_OUTPUT
          fi

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false
          enable-AzPSSession: false

      - name: Set Azure Subscription
        run: |
          echo "Setting Azure Subscription to: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

##############  Create Azure Backend ################
#####################################################

      - name: Create backend resources
        run: |
          # Retrieve environment variables from the GitHub Actions Environment
          environment="${{ vars.ENVIRONMENT }}"
          project_name="${{ vars.PROJECT_NAME }}"

          # Define variables for the backend resources
          az_backend_rg_name="${environment}-bkd-${project_name}"
          az_backend_sa_name="${environment}bkd${project_name}sa"
          az_backend_container_name="${environment}-bkd-${project_name}-co"
          az_location="SwitzerlandNorth"

          # Ensure storage account name is all lowercase and meets Azure's naming requirements
          az_backend_sa_name=$(echo "$az_backend_sa_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')


          # Print variable values for debugging (avoid printing secrets)
          echo "Resource Group Name: $az_backend_rg_name"
          echo "Storage Account Name: $az_backend_sa_name"
          echo "Container Name: $az_backend_container_name"

          # Re-set subscription context before resource group creation as an additional safeguard
          echo "Setting Azure Subscription to: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          # Create resource group if it doesn't exist
          az group create --name "$az_backend_rg_name" --location "$az_location"

          # Create storage account if it doesn't exist
          az storage account create \
            --name "$az_backend_sa_name" \
            --resource-group "$az_backend_rg_name" \
            --location "$az_location" \
            --sku Standard_LRS

