name: Destroy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev, qa, main)'
        required: true
        default: 'dev'

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Default permission for accessing the repo

jobs:
  destroy:
    name: Destroy Backend Resources
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: 'azurelanding'  # Sanitized project name (no hyphens)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variable
        id: setenv
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false
          enable-AzPSSession: false

      - name: Set Azure Subscription
        run: |
          echo "Setting Azure Subscription to: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Destroy backend resources
        run: |
          # Retrieve environment variables
          environment="${{ env.ENVIRONMENT }}"
          project_name=$(echo "${{ env.PROJECT_NAME }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')

          # Define variables for the backend resources
          az_backend_rg_name="${environment}-bkd-${project_name}"
          az_backend_sa_name="${environment}bkd${project_name}sa"
          az_location="SwitzerlandNorth"

          # Ensure storage account name is all lowercase and meets Azure's naming requirements
          az_backend_sa_name=$(echo "$az_backend_sa_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')
          # Truncate to 24 characters
          az_backend_sa_name=${az_backend_sa_name:0:24}

          # Print variable values for debugging (avoid printing secrets)
          echo "Resource Group Name to delete: $az_backend_rg_name"
          echo "Storage Account Name to delete: $az_backend_sa_name"

          # Delete storage account if it exists
          if az storage account check-name --name "$az_backend_sa_name" --query 'nameAvailable' | grep -q 'false'; then
            echo "Deleting storage account $az_backend_sa_name..."
            az storage account delete \
              --name "$az_backend_sa_name" \
              --resource-group "$az_backend_rg_name" \
              --yes
          else
            echo "Storage account $az_backend_sa_name does not exist."
          fi

          # Delete resource group if it exists
          if az group exists --name "$az_backend_rg_name"; then
            echo "Deleting resource group $az_backend_rg_name..."
            az group delete --name "$az_backend_rg_name" --yes --no-wait
          else
            echo "Resource group $az_backend_rg_name does not exist."
          fi
